server:
  port: 10211

spring:
  datasource:
    url: jdbc:mysql://119.3.218.87:3306/c4?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456Jack
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*.xml
  # type-aliases-package: team.workflow.general_backend.pojo


